apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp-api.fullname" . }}
  labels:
    {{- include "myapp-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "myapp-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "myapp-api.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets: 
      - name: myregistrykey

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.port }}
              protocol: TCP
