# variables:
#   IMAGE_NAME: monamp10/user-management
#   IMAGE_TAG: 1.0

stages:
  - test
  - build
  - deploy

run_test:
  stage: test
  image: golang:1.17
  script:
    - go test -v
    - go build main.go



build_image:
  stage: build
  before_script:
    - docker login -u "monamp10" -p "ArvanCloud1qaz!QAZ"
  script:
    - docker build -t monamp10/user-management:1.0 .
    - docker push monamp10/user-management:1.0

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
    - chmod 666 /var/run/docker.sock
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@188.121.109.78 "
        docker login -u "monamp10" -p "ArvanCloud1qaz!QAZ" &&
        docker rm -f usermanagement &&
        sudo docker run -d -p 18080:18080 --name usermanagement monamp10/user-management:1.0"