# variables:
#   IMAGE_NAME: monamp10/user-management
#   IMAGE_TAG: 1.0


run_test:
  image: golang:1.17
  script:
    - go test -v
    - go build main.go



build_image:
  before_script:
    - docker login -u "monamp10" -p "ArvanCloud1qaz!QAZ"
  script:
    - docker build -t monamp10/user-management:1.0 .
    - docker push monamp10/user-management:1.0