apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ include "maxscale2.name" . }}
    app.kubernetes.io/name: {{ include "maxscale2.name" . }}
  name: {{ include "maxscale2.fullname" . }}    
data:
  maxscale.cnf: |

    [server1]
    type     = server
    address  = mariadb-master
    port     = 3306
    protocol = MariaDBBackend
    proxy_protocol=yes

    [server2]
    type     = server
    address  = mariadb-slave
    port     = 3306
    protocol = MariaDBBackend
    proxy_protocol=yes


    [monitor]
    type                    = monitor
    module                  = mariadbmon
    servers                 = server1,server2
    user                    = maxscale
    password                = mypass
    auto_failover           = true
    auto_rejoin             = true
    enforce_read_only_slaves = 1

    [Splitter-Service]
    type=service
    router=readwritesplit
    servers=server1,server2
    user = maxscale
    password=mypass

    [Splitter-Listener]
    type=listener
    service=Splitter-Service
    protocol=MariaDBClient
    port=3306

